name: cmake

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }} | ${{ matrix.build_type }} | all_tests=ON
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true
      - name: Configure
        if: runner.os != 'Windows'
        run: >
          cmake -S . -B build-cmake
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DEVENTIDE_BUILD_ALL_TESTS=ON
          -G Ninja 
          -DCMAKE_CXX_COMPILER=clang-cl
          -DCMAKE_C_COMPILER=clang-cl

      - name: Configure (windows clang-cl)
        if: runner.os == 'Windows'
        run: >
          cmake -S . -B build-cmake
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DEVENTIDE_BUILD_ALL_TESTS=ON
          -G Ninja 
          -DCMAKE_CXX_COMPILER=clang-cl
          -DCMAKE_C_COMPILER=clang-cl

      - name: Build
        if: runner.os != 'Windows'
        run: cmake --build build-cmake

      - name: Build (windows)
        if: runner.os == 'Windows'
        run: cmake --build build-cmake --config ${{ matrix.build_type }}

      - name: Test
        if: runner.os != 'Windows'
        run: ./build-cmake/unit_tests

      - name: Test (windows)
        if: runner.os == 'Windows'
        run: .\build-cmake\unit_tests.exe
