name: xmake

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }} | mode=${{ matrix.mode }} | toolchain=${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]
        mode: [debug, release]
        toolchain: [default]
        include:
          - os: windows-2025
            mode: debug
            toolchain: clang-cl
          - os: windows-2025
            mode: release
            toolchain: clang-cl

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "3.0.5"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.toolchain }}
          package-cache: true
          package-cache-key: ${{ matrix.os }}-${{ matrix.mode }}-${{ matrix.toolchain }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true

      - name: Configure
        if: runner.os != 'macOS' && matrix.toolchain == 'default'
        run: >
          xmake config --clean --yes
          --mode=${{ matrix.mode }}
          --dev=y

      - name: Configure (windows clang-cl)
        if: runner.os == 'Windows' && matrix.toolchain == 'clang-cl'
        run: >
          xmake config --clean --yes
          --mode=${{ matrix.mode }}
          --toolchain=clang-cl
          --dev=y

      - name: Configure (macOS)
        if: runner.os == 'macOS' && matrix.toolchain == 'default'
        run: >
          xmake config --clean --yes
          --mode=${{ matrix.mode }}
          --toolchain=clang
          --dev=y

      - name: Build
        run: xmake --all --verbose --diagnosis

      - name: Test
        run: xmake test --verbose
