name: xmake

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.target.os }} | mode=${{ matrix.mode }} | toolchain=${{ matrix.target.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        mode: [debug, release]
        target:
          - os: windows-2025
            toolchain: clang-cl
            config_args: "--toolchain=clang-cl"
          - os: ubuntu-24.04
            toolchain: default
            config_args: ""
          - os: macos-15
            toolchain: default
            config_args: "--toolchain=clang"

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "3.0.5"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ matrix.target.os }}-${{ matrix.mode }}-${{ matrix.target.toolchain }}
          package-cache: true
          package-cache-key: ${{ matrix.target.os }}-${{ matrix.mode }}-${{ matrix.target.toolchain }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true

      - name: Configure
        run: >
          xmake config --clean --yes
          --mode=${{ matrix.mode }}
          ${{ matrix.target.config_args }}
          ${{ runner.os == 'Windows' && format('--sdk={0}\.pixi\envs\default\Library', github.workspace) || '' }}
          --dev=y
          --serde_simdjson=y
          --serde_flatbuffers=y

      - name: Build
        run: xmake --all --verbose --diagnosis

      - name: Test
        run: xmake test --verbose
